config/routes.rb
Onopia::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  get "management/index"

  resources :user_reset_passwords

  namespace(:admin){ resources :themes }

  namespace(:admin){ resources :account_types }

  resources :accounts

  get "configuration/index"
  get "home/index"
  get "users/amounts"
  get "users/records"
  
  match 'login' => 'home#login', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  
  match 'configuration' => 'configuration#index', :as => :configuration
  
  resources :users, :except => [:index] do
    member do
      post 'update_theme'
    end
  end
  
  resources :records, :only => [:update]
  resources :user_activates, :user_sessions
  resources :configuration, :only => [:index]
  
  scope "/admin", :module => "admin", :as => "admin" do
    resources :banks
  end
  
  resources :banks

  root :to => 'home#index'

end

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="errorExplanation">
    <ul>
    <% target.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_popup.html.erb
<% if target.errors.any? %>
  <script type="text/javascript">
    showMessage("<%= pluralize(target.errors.count, "erreur à été commise", "erreurs ont étés commises") %>", '<%= escape_javascript(render(:partial => "shared/error_messages", :locals => { :target => target } )) %>');
  </script>
<% end %>

app/views/shared/_javascript.html.erb
<% flash.each do |name, msg| %>
  <script type="text/javascript">
    showMessage("Information", "<%= msg %>");
  </script>
<% end %>
<div id="message"/>
<%= yield(:javascript) %>

app/views/shared/_menu.html.erb
<ul id="menu">
  <li><%= link_to "Accueil", root_path %></li>
  <li><%= link_to "Comptes", management_index_path %></li>
  <li><%= link_to "Configuration", configuration_path %></li>
  <li style="margin-left:500px">
    <%= link_to(image_tag("logout.png"),
                 user_session_path(@current_user), 
                 :method => :delete, 
                 :id => "delete")
    %>
  </li>
</ul>

<script id="scriptInit" type="text/javascript">
  $(document).ready(function () {
    $("#menu").wijmenu();
  });
  <% (position + 1).times do %>
    $(document).ready(function($) {
      $("#menu").focus().wijmenu("next");
    });
  <% end %>
</script>

app/views/shared/_stats.html.erb
<% content_for(:javascript_library) do %>
  <%= javascript_include_tag 'datatables' %>
  <%= javascript_include_tag 'highcharts' %>
<% end %>
<% content_for(:javascript) do %>
  <script>
    $(document).ready(function() {
      changeYear(<%= year %>);
    });
  </script>
<% end %>
<table width="100%">
  <tr>
    <td colspan="2"><div id="container_year" style="margin:auto; width:740px; height:260px"></div></td>
  </tr>
  <tr>
    <td><div id="container_incomes" style="margin:auto; width:350px;height:300px"></div></td>
    <td><div id="container_expenses" style="margin:auto; width:350px;height:300px"></div></td>
  </tr>
  <tr>
    <td colspan="2">
      <table cellpadding="0" cellspacing="0" border="0" class="display" id="list-records">
	      <thead>
		      <tr>
			      <th width="12%">Date</th>
			      <th width="70%">Libellé</th>
			      <th width="8%">Montant</th>
			      <th width="10%">Categorie</th>
		      </tr>
	      </thead>
	      <tbody>
		
	      </tbody>
	      <tfoot>
		      <tr>
			      <th>Date</th>
			      <th>Libellé</th>
			      <th>Montant</th>
			      <th>Categorie</th>
		      </tr>
	      </tfoot>
      </table>
    </td>
  </tr>
<table>